# Generated by Django 4.2.7 on 2023-12-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
