# Generated by Django 4.2.7 on 2023-12-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='quantity',
        ),
    ]
