# Generated by Django 4.2.7 on 2023-12-05 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_level_category_lft_category_rght_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_favorits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorits',
            new_name='Favorites',
        ),
    ]
